# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
#  codecov: codecov/codecov@3.2.3

jobs:
  build:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: npm install
      - run:
          name: 'JavaScript Linter'
          command: npx eslint --format junit -o reports/junit/eslint.xml src/*.ts test/*
      - run:
          name: 'Run Jest and Collect Coverage Reports'
          command: |
            ./cc-test-reporter before-build
            npx jest
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: coverage
#      - codecov/upload:
#          file: ./coverage/lcov.info
